name: gbc
channels:
  - defaults
dependencies:
  - python
  - jupyterlab
  - pandas
  - yaml
  - pyyaml
  - sqlalchemy
  - tqdm
  - mysql
  - mysql-connector-python
  - notebook
  - pyzmq
  - openssl
  - blas
  - protobuf
  - jupyter_server
  - mistune
  - urllib3
  - jupyter_client
  - libprotobuf
